apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appdemo
  name: appdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appdemo
    spec:
      containers:
      - image: nginx:latest
        name: appdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    app: test-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: appdemo
